apiVersion: v1
kind: Service
metadata:
  name: {{ include "devchart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "devchart.labels" . | nindent 4 }}
spec:
  {{- range .Values.service.ports }}
  type: {{ .type | default "ClusterIP" }}  
  ports:
    - name: {{ .name }}
      port: {{ .port }}
      {{- if .containerPort }}
      containerPort: {{ .containerPort | default .port }}      
      {{- end }}      
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    {{- include "devchart.selectorLabels" . | nindent 4 }}
