name: Sync Main Branch to Public Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Push to public repository
      run: |
        # Configure git with user credentials
        git config --global user.name "kamleshbelote"
        git config --global user.email "your-email@example.com"
        
        # Clone the public repository
        git clone https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/kamleshbelote/HelmChart-public.git public-repo
        
        # Copy files (excluding .git directory)
        rsync -av --exclude='.git' --exclude='public-repo' ./ public-repo/
        
        # Push changes
        cd public-repo
        git add .
        git commit -m "Sync from private repo: $(date)" || echo "No changes to commit"
        git push origin main
